font-size: [ p-fsize-small, p-fsize-medium, p-fsize-large ]
font-style: [ p-fstyle-normal, p-fstyle-italic ]
font-weight: [ p-fw-normal, p-fw-bold ]
v-align: [ p-va-top, p-va-middle, p-va-bottom ]
padding: [ p-pad-0, p-pad-10, p-pad-20 ]
img-proportions: [ squared, portrait, landscape ]