font-size: [ p-fsize-small, p-fsize-medium, p-fsize-large ]
font-style: [ p-fstyle-normal, p-fstyle-italic ]
font-weight: [ p-fw-normal, p-fw-bold ]
v-align: [ p-va-top, p-va-middle, p-va-bottom ]
align-items: [ p-aitem-start, p-aitem-center, p-aitem-end]
padding: [ p-pad-0, p-pad-10, p-pad-20 ]
img-proportions: [ img-squared, img-portrait, img-landscape ]
flex-dir: [ p-flex-dir-row, p-flex-dir-col ]